version: '3'
services:
  web:
    container_name: wiam-nginx
    image: nginx
    restart: always
    volumes:
      - ./docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - php
  php:
    container_name: wiam-php
    image: devilbox/php-fpm:8.2-mods
    restart: always
    command: bash -c "curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && /usr/local/sbin/php-fpm"
    volumes:
      - ./public:/var/www/html
      - ./docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
  db:
    container_name: wiam-pgsql
    image: postgres:15.5
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./docker/db:/var/lib/postgresql/data